### ISSUE TITLE
Extra line of code in HTML

### ISSUE THREAD

**Issue by juliabrowne** [Juett/insta-news#1]
This line isn't needed since your font files are already in your minimized CSS:

https://github.com/Juett/insta-news/blob/927ae5fdbe2de1a6c91eff19c9a54a65561a8bcd/index.html#L10-L11

**Comment by juliabrowne** [comment]
No error message. To include one, go into your JS file and add this:

      .fail(function (err) {
        alert('Oops, something went wrong. Please try again!');
      })

**Comment by juliabrowne** [comment]
Your "Sections..." page isn't resetting to default when it's selected. The header stays in the same spot instead of resetting to a larger size.

**Comment by rcass** [comment]
Just a minor point with this issue. It is extra because we are not using font awesome in this project. 

If this project was using font awesome, then yes you could include it like so. It is independent of the sass partials that are compiling to the minified file.

**Comment by rcass** [comment]
Confused as to why this issue is closed since this line of code is still in the project 🤔 
https://github.com/Juett/insta-news/blob/310929616d633322d9a39bbffe22cbfd236a6113/index.html#L10
