### ISSUE TITLE
No error message

### ISSUE THREAD

**Issue by juliabrowne** [Juett/insta-news#2]
No error message. To include one, go into your JS file and add this:

      .fail(function (err) {
        alert('Oops, something went wrong. Please try again!');
      })

**Comment by rcass** [comment]
Another idea of a more elegant error message would be appending a text to the page, saying something went wrong and to make another selection.

**Comment by rcass** [comment]
I noticed you added this:
https://github.com/Juett/insta-news/blob/310929616d633322d9a39bbffe22cbfd236a6113/js/index.js#L59-L60

That is a good start but doesn't really tell the user that something went wrong. Please add to this so the user has a clear idea that something went wrong.
